### ISSUE TITLE
Error ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by shivanshu-semwal** [Schrodinger-Hat/ImageGoNord-pip#4]
I tried using custom palette.

Here is the python code I used:

```py
#!/usr/bin/env python3

import os 
from ImageGoNord import NordPaletteFile, GoNord

dir_path = os.path.dirname(os.path.realpath(__file__))
# palette = dir_path+'/palettes/Gruvbox.txt'
dir_path = dir_path+'/palettes/'
# documentation of ImageGoNord - https://github.com/Schrodinger-Hat/ImageGoNord-pip/tree/master/docs
# E.g. Replace pixel by pixel
go_nord = GoNord()
go_nord.set_palette_lookup_path(dir_path)
# go_nord.reset_palette();

go_nord.add_file_to_palette("Gruvbox.txt")

bug=go_nord.get_palette_data()
print(bug)
```

Here is the directory structure:
```
~
|--Scripts
|--|--palettes
|--|--|--Aurora.txt
|--|--|--Frost.txt
|--|--|--Gruvbox.txt
|--|--|--PolarNight.txt
|--|--|--SnowStorm.txt
|--|--image_nord.py
```
And this is the contents of `Gruvbox.txt`
```
#fb4934
#b8bb26
#fabd2f
#83a598
#d3869b
#8ec07c
#ebdbb2
```

```
Traceback (most recent call last):
  File "./image_nord.py", line 15, in <module>
    go_nord.add_file_to_palette("Gruvbox.txt")
  File "/home/antihero/.local/lib/python3.8/site-packages/ImageGoNord/GoNord.py", line 189, in add_file_to_palette
    self.get_palette_data()
  File "/home/antihero/.local/lib/python3.8/site-packages/ImageGoNord/GoNord.py", line 170, in get_palette_data
    hex_colors = pl.import_palette_from_file(
  File "/home/antihero/.local/lib/python3.8/site-packages/ImageGoNord/utility/palette_loader.py", line 74, in import_palette_from_file
    palette.remove('')
ValueError: list.remove(x): x not in list
```

How can I fix this? Also when I installed the pip package there were no `palette` folder, I had to download it from repo.

**Comment by TheJoin95** [comment]
I see. I'll try to verify the package file because I was sure that I inserted also the palettes file.
In the meantime, in order to fix the issue, you can add at your `Gruvbox.txt` file 2 empty lines, like this:
```
#fb4934
#b8bb26
#fabd2f
#83a598
#d3869b
#8ec07c
#ebdbb2


```

I'm gonna check the package as soon as I can, thank you for the issue

**Comment by shivanshu-semwal** [comment]
Thanks adding 2 empty entries fixed my issue.  (so every palette require 9 entries)
